### ISSUE TITLE
Rust rz-pipe shouldn't panic

### ISSUE THREAD

**Issue by spacemeowx2** [rizinorg/rz-pipe#11]
As a library, rz-pipe should not panic user's process.

All uses of `unwrap` and `expect` should be removed. Use error instead.

https://github.com/rizinorg/rz-pipe/blob/76e7b67456aa73770478c0161a230b2ed6420145/rust/src/rzpipe.rs#L216

https://github.com/rizinorg/rz-pipe/blob/76e7b67456aa73770478c0161a230b2ed6420145/rust/src/rzpipe.rs#L265-L272

https://github.com/rizinorg/rz-pipe/blob/76e7b67456aa73770478c0161a230b2ed6420145/rust/src/rzpipe.rs#L332-L337

https://github.com/rizinorg/rz-pipe/blob/76e7b67456aa73770478c0161a230b2ed6420145/rust/src/rzpipe.rs#L354

https://github.com/rizinorg/rz-pipe/blob/76e7b67456aa73770478c0161a230b2ed6420145/rust/src/rz.rs#L21

**Comment by 4thel00z** [comment]
Pls review @XVilka / @spacemeowx2 and pardon my rust n00bness lel

**Comment by XVilka** [comment]
@spacemeowx2 does this still happen?
