### ISSUE TITLE
iVj results in error

### ISSUE THREAD

**Issue by geekscrapy** [rizinorg/rz-pipe#31]
```
>>> import rzpipe
>>> rzpipe.open('/usr/bin/true', flags=['-2']).cmdj('iVj')
rzpipe.cmdj.Error: Expecting value: line 2 column 1 (char 1)
```

/usr/bin/true is https://www.virustotal.com/gui/file/409b33a9b8702e77546c44d58362011d0634ef8dd811975e42a5ed01bd748fcb

**Comment by geekscrapy** [comment]
Looks like it doesn't produce valid json:

```
>>> rzpipe.open('/usr/bin/true', flags=['-2']).cmd('iVj')
'\n'
>>> rzpipe.open('/usr/bin/true', flags=['-2']).cmd('iV')
''
```

**Comment by geekscrapy** [comment]
Same error with iTj and iRj

**Comment by wargio** [comment]
`ìT` is not a valid command and the other 2 works on mine.

**Comment by geekscrapy** [comment]
I'm on Mac 10.15.7
0.3.0  rizin
Python 3.7.10

> `ìT` is not a valid command and the other 2 works on mine.
The `i` in the comment is the wrong type: `ìT` vs `iT`
`iT` is the File Signature analysis

Did you try with that specific file?

**Comment by wargio** [comment]
i think you are on 0.2.x run `rizin -v` because that output is from the oldshell not newshell.

**Comment by geekscrapy** [comment]
There are multiple ways that items are returned from iVj it seems
```
>>> o = rzpipe.open('radare2-testbins/pe/base.exe', flags=['-2'])

>>> str(o.cmdj('iVj'))
'{}'
```

**Comment by wargio** [comment]
can you open the bin in rizin and just return here the following output?
```
rizin /usr/bin/true
i?
iVj
```
